//
// Generated file, do not edit! Created by nedtool 5.4 from timePacket.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __TIMEPACKET_M_H
#define __TIMEPACKET_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>timePacket.msg:16</tt> by nedtool.
 * <pre>
 * packet TimePacket
 * {
 *     double time;
 * }
 * </pre>
 */
class TimePacket : public ::omnetpp::cPacket
{
  protected:
    double time;

  private:
    void copy(const TimePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TimePacket&);

  public:
    TimePacket(const char *name=nullptr, short kind=0);
    TimePacket(const TimePacket& other);
    virtual ~TimePacket();
    TimePacket& operator=(const TimePacket& other);
    virtual TimePacket *dup() const override {return new TimePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getTime() const;
    virtual void setTime(double time);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TimePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TimePacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __TIMEPACKET_M_H

